[package]
name = "otelwasm-rust-example-webhookeventreceiver"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
otelwasm-rust-sdk = { path = "../../crates/otelwasm-rust-sdk", features = ["socket-extension"] }
opentelemetry-proto = { version = "0.31.0", default-features = false, features = ["gen-tonic-messages", "logs"] }
prost = "0.14"
serde.workspace = true
serde_json.workspace = true
